### ISSUE TITLE
Issue with context null pointer

### ISSUE THREAD

**Issue by USER4247** [Fox520/pushyy#4]
Sometimes when app is in background or not running at all , when a background notification is recieved , background service never runs , but sometimes it does . Here is error reported by Android 13 java.lang.RuntimeException: Unable to create service org.kivy.plugins.messaging.
KivyFirebaseMessagingBackgroundService:
java.lang.NullPointerException: Attempt
to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a
null object reference
at
android.app.ActivityThread.handleCreateService(Ac
tivityThread.java:4786)
at android.app.ActivityThread.-$ $Nest$mhandleCreateService(Unknown Source:0)
at
android.app.ActivityThread$H.handleMessage(Activ
ityThread.java:2272)
at
android.os.Handler.dispatchMessage(Handler.java:
106)
at android.os.Looper.loopOnce (Looper.java:211) at android.os.Looper.loop(Looper.java:300)
at
android.app.ActivityThread.main(ActivityThread.jav
a:8432)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndAr
gsCaller.run(RuntimeInit.java:560)
at
com.android.internal.os.ZygoteInit.main(Zygotelnit.j
ava:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a
null object reference
at
android.content.ComponentName.<init>(Componen
tName.java:132)
at android.content.Intent.<init>(Intent.java:7422)

**Comment by luksus42** [comment]
I am running into the same issue.

Or maybe not the same, but similar:
```
10-20 14:14:43.364 14314 14314 D FLTFireMsgReceiver: broadcast received for message
10-20 14:14:43.364 14314 14314 D KVFireContextHolder: received application context.
10-20 14:14:43.405 14314 14314 D AndroidRuntime: Shutting down VM
10-20 14:14:43.411 14314 14314 E AndroidRuntime: FATAL EXCEPTION: SDLActivity
10-20 14:14:43.411 14314 14314 E AndroidRuntime: Process: org.xyz.test, PID: 14314
10-20 14:14:43.411 14314 14314 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.kivy.plugins.messaging.KivyFirebaseMessagingReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.messaging.RemoteMessage$Notification.getTitle()' on a null object reference
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.messaging.RemoteMessage$Notification.getTitle()' on a null object reference
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at org.kivy.plugins.messaging.KivyFirebaseMessagingReceiver.onReceive(KivyFirebaseMessagingReceiver.java:36)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
10-20 14:14:43.411 14314 14314 E AndroidRuntime: 	... 8 more
```

**Comment by ProtDos** [comment]
Same here. Any fix?
